<?php

namespace testnamespace\contact;

use Illuminate\Support\ServiceProvider;

class ContactServiceProvider extends ServiceProvider {

    public function boot(){
        //load routes die zum package gehöhren
        $this->loadRoutesFrom(__DIR__.'/routes/web.php');

        //Ort, an dem die Views liegen des Packages - 1. parameter: ordnername, 2. parameter: paketname, in dem der ordner liegt
        $this->loadViewsFrom(__DIR__.'/views', 'contact');

        $this->loadMigrationsFrom(__DIR__.'/database/migrations');
    }

    public function register() {
        parent::register(); // TODO: Change the autogenerated stub
    }


}